<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateItemtext extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('itemtext', function (Blueprint $table) {
            $table->increments('iid');
            $table->integer('itemTextID');
            $table->integer('itemID');
            $table->string('folderkey', 50)->nullable();
            $table->string('filekey', 50)->nullable();
            $table->longtext('xmlText')->nullable();
            $table->string('aa', 50)->nullable();
            $table->longtext('ab')->nullable();
            $table->string('ac', 50)->nullable();
            $table->string('ad', 50)->nullable();
            $table->longtext('ae')->nullable();
            $table->longtext('af')->nullable();
            $table->longtext('ag')->nullable();
            $table->string('ah', 30)->nullable();
            $table->string('ai', 50)->nullable();
            $table->longtext('aj')->nullable();
            $table->string('ak', 50)->nullable();
            $table->string('al', 50)->nullable();
            $table->string('am', 50)->nullable();
            $table->longtext('an')->nullable();
            $table->longtext('ao')->nullable();
            $table->longtext('ap')->nullable();
            $table->longtext('aq')->nullable();
            $table->longtext('ar')->nullable();
            $table->longtext('at')->nullable();
            $table->longtext('au')->nullable();
            $table->longtext('av')->nullable();
            $table->longtext('aw')->nullable();
            $table->longtext('ax')->nullable();
            $table->longtext('ay')->nullable();
            $table->longtext('az')->nullable();
            $table->longtext('ba')->nullable();
            $table->longtext('bb')->nullable();
            $table->longtext('bc')->nullable();
            $table->string('bd', 50)->nullable();
            $table->string('be', 50)->nullable();
            $table->longtext('bf')->nullable();
            $table->longtext('bg')->nullable();
            $table->longtext('bh')->nullable();
            $table->longtext('bi')->nullable();
            $table->longtext('bj')->nullable();
            $table->longtext('bk')->nullable();
            $table->longtext('bl')->nullable();
            $table->longtext('bm')->nullable();
            $table->longtext('bn')->nullable();
            $table->longtext('bo')->nullable();
            $table->longtext('bp')->nullable();
            $table->longtext('bq')->nullable();
            $table->longtext('br')->nullable();
            $table->longtext('bs')->nullable();
            $table->longtext('bt')->nullable();
            $table->longtext('bu')->nullable();
            $table->longtext('bv')->nullable();
            $table->longtext('bw')->nullable();
            $table->string('bx', 50)->nullable();
            $table->longtext('bz')->nullable();
            $table->longtext('ca')->nullable();
            $table->string('cb', 50)->nullable();
            $table->longtext('cc')->nullable();
            $table->longtext('cd')->nullable();
            $table->longtext('ce')->nullable();
            $table->longtext('cf')->nullable();
            $table->string('cg', 50)->nullable();
            $table->string('ch', 50)->nullable();
            $table->string('ci', 50)->nullable();
            $table->string('cj', 50)->nullable();
            $table->longtext('ck')->nullable();
            $table->longtext('cl')->nullable();
            $table->longtext('cm')->nullable();
            $table->longtext('cn')->nullable();
            $table->longtext('co')->nullable();
            $table->longtext('cp')->nullable();
            $table->longtext('cq')->nullable();
            $table->longtext('cr')->nullable();
            $table->longtext('cs')->nullable();
            $table->longtext('ct')->nullable();
            $table->longtext('cu')->nullable();
            $table->longtext('cv')->nullable();
            $table->longtext('cw')->nullable();
            $table->longtext('cx')->nullable();
            $table->longtext('cy')->nullable();
            $table->longtext('cz')->nullable();
            $table->longtext('da')->nullable();
            $table->longtext('db')->nullable();
            $table->longtext('dc')->nullable();
            $table->longtext('dd')->nullable();
            $table->longtext('de')->nullable();
            $table->longtext('df')->nullable();
            $table->longtext('dg')->nullable();
            $table->longtext('dh')->nullable();
            $table->longtext('di')->nullable();
            $table->longtext('dj')->nullable();
            $table->longtext('dk')->nullable();
            $table->longtext('dl')->nullable();
            $table->longtext('dm')->nullable();
            $table->longtext('dn')->nullable();
            $table->longtext('do')->nullable();
            $table->longtext('dp')->nullable();
            $table->longtext('dq')->nullable();
            $table->longtext('dr')->nullable();
            $table->longtext('ds')->nullable();
            $table->longtext('dt')->nullable();
            $table->longtext('du')->nullable();
            $table->longtext('dv')->nullable();
            $table->longtext('dw')->nullable();
            $table->longtext('dx')->nullable();
            $table->longtext('dy')->nullable();
            $table->longtext('dz')->nullable();
            $table->longtext('ea')->nullable();
            $table->longtext('eb')->nullable();
            $table->longtext('ec')->nullable();
            $table->longtext('ed')->nullable();
            $table->longtext('ee')->nullable();
            $table->longtext('ef')->nullable();
            $table->longtext('eg')->nullable();
            $table->longtext('eh')->nullable();
            $table->longtext('ei')->nullable();
            $table->longtext('ej')->nullable();
            $table->longtext('ek')->nullable();
            $table->longtext('el')->nullable();
            $table->longtext('em')->nullable();
            $table->string('en',50)->nullable();
            $table->longtext('eo')->nullable();
            $table->longtext('ep')->nullable();
            $table->longtext('eq')->nullable();
            $table->string('er',50)->nullable();
            $table->longtext('es')->nullable();
            $table->longtext('et')->nullable();
            $table->longtext('eu')->nullable();
            $table->string('ev',50)->nullable();
            $table->longtext('ew')->nullable();
            $table->longtext('ex')->nullable();
            $table->longtext('ey')->nullable();
            $table->longtext('ez')->nullable();
            $table->longtext('fa')->nullable();
            $table->longtext('fb')->nullable();
            $table->longtext('fc')->nullable();
            $table->string('fd',50)->nullable();
            $table->longtext('fe')->nullable();
            $table->longtext('ff')->nullable();
            $table->longtext('fg')->nullable();
            $table->longtext('fh')->nullable();
            $table->longtext('fi')->nullable();
            $table->string('fj',50)->nullable();
            $table->longtext('fk')->nullable();
            $table->longtext('fl')->nullable();
            $table->longtext('fm')->nullable();
            $table->longtext('fn')->nullable();
            $table->longtext('fo')->nullable();
            $table->longtext('fp')->nullable();
            $table->longtext('fq')->nullable();
            $table->longtext('fr')->nullable();
            $table->longtext('fs')->nullable();
            $table->longtext('ft')->nullable();
            $table->longtext('fu')->nullable();
            $table->longtext('fv')->nullable();
            $table->longtext('fw')->nullable();
            $table->longtext('fx')->nullable();
            $table->longtext('fy')->nullable();
            $table->longtext('fz')->nullable();
            $table->longtext('ga')->nullable();
            $table->longtext('gb')->nullable();
            $table->longtext('gc')->nullable();
            $table->longtext('gd')->nullable();
            $table->longtext('ge')->nullable();
            $table->longtext('gf')->nullable();
            $table->longtext('gg')->nullable();
            $table->longtext('gh')->nullable();
            $table->longtext('gi')->nullable();
            $table->longtext('gj')->nullable();
            $table->longtext('gk')->nullable();
            $table->longtext('gl')->nullable();
            $table->longtext('gm')->nullable();
            $table->longtext('gn')->nullable();
            $table->longtext('go')->nullable();
            $table->longtext('gp')->nullable();
            $table->longtext('gq')->nullable();
            $table->longtext('gr')->nullable();
            $table->longtext('gs')->nullable();
            $table->longtext('gt')->nullable();
            $table->longtext('gu')->nullable();
            $table->longtext('gv')->nullable();
            $table->longtext('gw')->nullable();
            $table->longtext('gx')->nullable();
            $table->longtext('gy')->nullable();
            $table->longtext('gz')->nullable();
            $table->longtext('ha')->nullable();
            $table->longtext('hb')->nullable();
            $table->longtext('hc')->nullable();
            $table->longtext('hd')->nullable();
            $table->longtext('he')->nullable();
            $table->longtext('hf')->nullable();
            $table->longtext('hg')->nullable();
            $table->longtext('hh')->nullable();
            $table->longtext('hi')->nullable();
            $table->longtext('hj')->nullable();
            $table->longtext('hk')->nullable();
            $table->longtext('hl')->nullable();
            $table->longtext('hm')->nullable();
            $table->longtext('hn')->nullable();
            $table->longtext('ho')->nullable();
            $table->longtext('hp')->nullable();
            $table->longtext('hq')->nullable();
            $table->longtext('hr')->nullable();
            $table->longtext('hs')->nullable();
            $table->longtext('ht')->nullable();
            $table->longtext('hu')->nullable();
            $table->longtext('hv')->nullable();
            $table->longtext('hx')->nullable();
            $table->longtext('hy')->nullable();
            $table->longtext('hz')->nullable();
            $table->longtext('ia')->nullable();
            $table->longtext('ib')->nullable();
            $table->longtext('ic')->nullable();
            $table->longtext('id')->nullable();
            $table->longtext('ie')->nullable();
            $table->longtext('ig')->nullable();
            $table->longtext('ih')->nullable();
            $table->longtext('ii')->nullable();
            $table->longtext('ij')->nullable();
            $table->longtext('ik')->nullable();
            $table->longtext('il')->nullable();
            $table->longtext('im')->nullable();
            $table->longtext('ip')->nullable();
            $table->longtext('iq')->nullable();
            $table->longtext('ir')->nullable();
            $table->longtext('it')->nullable();
            $table->longtext('iu')->nullable();
            $table->longtext('iv')->nullable();
            $table->longtext('iw')->nullable();
            $table->longtext('ix')->nullable();
            $table->longtext('iy')->nullable();
            $table->longtext('iz')->nullable();
            $table->longtext('ja')->nullable();
            $table->longtext('jb')->nullable();
            $table->longtext('jc')->nullable();
            $table->longtext('jd')->nullable();
            $table->longtext('je')->nullable();
            $table->longtext('jf')->nullable();
            $table->longtext('jg')->nullable();
            $table->longtext('jh')->nullable();
            $table->longtext('ji')->nullable();
            $table->longtext('jj')->nullable();
            $table->longtext('jk')->nullable();
            $table->longtext('jl')->nullable();
            $table->longtext('jm')->nullable();
            $table->longtext('jn')->nullable();
            $table->longtext('jo')->nullable();
            $table->longtext('jp')->nullable();
            $table->longtext('creator')->nullable();
            $table->longtext('others')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('itemtext');
    }
}
